### PR TITLE
Support shared parameters

### PR DESCRIPTION
**Pull request by myleott**
Thanks for sharing this, it's very useful :)

I noticed it doesn't support shared params currently. Added a test and support for shared params. Feedback welcome if there's a cleaner way to do this.

### CODE REVIEW

**Comment by SsnL** [comment]
Thanks Myle! I think this doesn't work if a parameter is shared more than once. It doesn't seem hard to support the general case. Could you please make that change?  Or maybe I am wrong and it is hard to do so....

**Comment by myleott** [comment]
> I think this doesn't work if a parameter is shared more than once

Do you mean something like this?
```python
net = torch.nn.Sequential(
    torch.nn.Linear(10, 10, bias=False),
    torch.nn.Linear(10, 10, bias=False),
    torch.nn.Linear(10, 10, bias=False),
    torch.nn.Linear(10, 10, bias=False),
)
# last two layers share weights with the first
net[-1].weight = net[0].weight
net[-2].weight = net[0].weight
```

This seems to work currently, maybe I am misunderstanding?

**Comment by SsnL** [comment]
Oh it does indeed. I misunderstood `shared_param_infos `. Sorry about that.

**Review by ssnl — APPROVED** [review]
Thanks a lot!

**Pull request merged**
